# 01. Знакомство с `torch.Tensor`

---

При решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использование функционала библиотеки `torch`.

[PyTorch documentation](https://pytorch.org/docs/stable/#pytorch-documentation)

In [1]:
import numpy as np
import torch

In [2]:
import sys
sys.version_info

sys.version_info(major=3, minor=10, micro=7, releaselevel='final', serial=0)

## 1.1 Создание тензоров и выполнение базовых операций над ними

[Документация по функциям для создания тензоров](https://pytorch.org/docs/stable/torch.html#creation-ops)

[Документация по функциям для работы с индексами](https://pytorch.org/docs/stable/torch.html#indexing-slicing-joining-mutating-ops)

1.1.1 Создайте двумерный тензор размера (8, 8). Используя как можно меньше операций, добейтесь расстановки кодов "шахматных фигур".

Ожидаемый результат:

```
[[-4., -3., -2., -6., -5., -2., -3., -4.],
 [-1., -1., -1., -1., -1., -1., -1., -1.],
 [0., 0., 0., 0., 0., 0., 0., 0.],
 [0., 0., 0., 0., 0., 0., 0., 0.],
 [0., 0., 0., 0., 0., 0., 0., 0.],
 [0., 0., 0., 0., 0., 0., 0., 0.],
 [1., 1., 1., 1., 1., 1., 1., 1.],
 [4., 3., 2., 6., 5., 2., 3., 4.]]

```

In [3]:
task1 = torch.zeros((8, 8))
task1

tensor([[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]])

In [4]:
task1[0] = torch.as_tensor([-4., -3., -2., -6., -5., -2., -3., -4.])
task1[1] = -1
task1[-2] = task1[1] * -1
task1[-1] = task1[0] * -1
task1

tensor([[-4., -3., -2., -6., -5., -2., -3., -4.],
        [-1., -1., -1., -1., -1., -1., -1., -1.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
        [ 4.,  3.,  2.,  6.,  5.,  2.,  3.,  4.]])

1.1.2 Средствами `torch` рассчитать произведения четных чисел от 2 до 20 на ближайшие к ним бОльшие нечетные числа.

In [5]:
data = torch.arange(2, 21)
x = data[data % 2 == 0]
y = x + 1
z = x * y
z

tensor([  6,  20,  42,  72, 110, 156, 210, 272, 342, 420])

1.1.3 Создать тензор размера 11x7 вида: [[1, 2, 3, ..., 7], [11, 12, 13, ..., 17], [21, 22, 23, ..., 27], ..., [101, 102, 103, ..., 107]]

In [7]:
x = torch.arange(0, 7)
y = torch.arange(1, 110, 10)
x.unsqueeze(1) + y

tensor([[  1,  11,  21,  31,  41,  51,  61,  71,  81,  91, 101],
        [  2,  12,  22,  32,  42,  52,  62,  72,  82,  92, 102],
        [  3,  13,  23,  33,  43,  53,  63,  73,  83,  93, 103],
        [  4,  14,  24,  34,  44,  54,  64,  74,  84,  94, 104],
        [  5,  15,  25,  35,  45,  55,  65,  75,  85,  95, 105],
        [  6,  16,  26,  36,  46,  56,  66,  76,  86,  96, 106],
        [  7,  17,  27,  37,  47,  57,  67,  77,  87,  97, 107]])

1.1.4 Написать функцию, которая для целых значений `n` и `m` будет возвращать тензор размера `n`x`m`, заполненный текстурой размера 2x2, состоящей из следующих значений:

```
0 1

2 3

```

Пример для n = 4 и m = 5:

```
0 1 0 1 0

2 3 2 3 2

0 1 0 1 0

2 3 2 3 2
```

In [8]:
n = 4
m = 5

In [214]:
base = torch.as_tensor([[0, 1], [2, 3]])
base.repeat(n, m)[:n, :m]

tensor([[0, 1, 0, 1, 0],
        [2, 3, 2, 3, 2],
        [0, 1, 0, 1, 0],
        [2, 3, 2, 3, 2]])

1.1.5 Сгенерировать двумерный тензор `t` размерности (4, 7), состоящий из случайных действительных чисел, равномерно распределенных в дипазоне от 0 до 20. Нормализовать значения массива с помощью преобразования вида $ax+b$ так, что после нормализации максимальный элемент масива будет равен 1.0, минимальный 0.0

In [225]:
a = torch.randint(0, 21, (4, 7), dtype=float)
a

tensor([[ 9.,  8.,  0., 10., 14.,  1., 20.],
        [20.,  3.,  0., 12., 12.,  7.,  7.],
        [ 7., 19.,  9., 17.,  7.,  3., 18.],
        [13., 11.,  2., 13.,  0., 11., 12.]], dtype=torch.float64)

In [254]:
torch.nn.functional.normalize(a, 16)

tensor([[0.4499, 0.3999, 0.0000, 0.4999, 0.6999, 0.0500, 0.9998],
        [1.0000, 0.1500, 0.0000, 0.6000, 0.6000, 0.3500, 0.3500],
        [0.3579, 0.9714, 0.4602, 0.8692, 0.3579, 0.1534, 0.9203],
        [0.9464, 0.8008, 0.1456, 0.9464, 0.0000, 0.8008, 0.8736]],
       dtype=torch.float64)

[Random Sampling](https://pytorch.org/docs/stable/torch.html#random-sampling)

[Distributions](https://pytorch.org/docs/stable/distributions.html)

1.1.6 Задать два двумерных тензора `ar1` и `ar2` размерности (4, 7), состоящих из случайных целых чисел в пределах от 0 до 10. Построить двумерный тензор размерности (4, 7), каждый элемент которого представляет собой максимум из двух значений, находящихся на аналогичной позиции в массивах `ar1`, `ar2`.

[Reductions ops](https://pytorch.org/docs/stable/torch.html#reduction-ops)

In [212]:
ar1 = torch.randint(0, 10, (4, 7))
ar2 = torch.randint(0, 10, (4, 7))
ar1, ar2

(tensor([[3, 5, 6, 6, 5, 3, 1],
         [1, 7, 7, 2, 0, 8, 0],
         [3, 2, 9, 0, 7, 1, 2],
         [4, 4, 7, 2, 9, 1, 6]]),
 tensor([[6, 6, 1, 2, 4, 1, 1],
         [4, 3, 8, 8, 6, 8, 1],
         [5, 6, 4, 3, 6, 1, 4],
         [9, 2, 1, 1, 0, 3, 9]]))

In [213]:
torch.where(ar1>ar2, ar1, ar2)

tensor([[6, 6, 6, 6, 5, 3, 1],
        [4, 7, 8, 8, 6, 8, 1],
        [5, 6, 9, 3, 7, 1, 4],
        [9, 4, 7, 2, 9, 3, 9]])

1.1.7 Создать тензор из 20 случайных целых чисел от 0 до 100. Получить второе сверху значение в тензоре. Определить индекс этого значения.

In [208]:
x = torch.randint(0, 101, (20, ))
values, indices = x.sort()
x

tensor([88,  7,  4, 33, 78, 43, 15, 27, 91,  1, 87, 41, 40, 58, 70, 88, 50,  0,
        43, 24])

In [209]:
x.sort()

torch.return_types.sort(
values=tensor([ 0,  1,  4,  7, 15, 24, 27, 33, 40, 41, 43, 43, 50, 58, 70, 78, 87, 88,
        88, 91]),
indices=tensor([17,  9,  2,  1,  6, 19,  7,  3, 12, 11,  5, 18, 16, 13, 14,  4, 10,  0,
        15,  8]))

In [210]:
values[-1], indices[-1]

(tensor(91), tensor(8))

## 1.2 Распространение

[Numpy broadcasting](https://numpy.org/devdocs/user/theory.broadcasting.html)

[Torch broadcasting](https://pytorch.org/docs/stable/notes/broadcasting.html)

1.2.1 Создать тензор 11x7 вида: `[[1, 2, 3, ..., 7], [11, 12, 13, ..., 17], [21, 22, 23, ..., 27], ..., [101, 102, 103, ..., 107]]`. При решении задачи применить технику распространения.

1.2.2 Вычесть одномерный тензор `b_1d` из двухмерного тензора `a_2d`, так, чтобы каждый элемент одномерного тензора вычитался из всех элементов соответствующих строк двумерного тензора.

_Пример:_

Для входа:
```python
a_2d = np.array([[3,3,3],[4,4,4],[5,5,5]])
b_1d = np.array([1,2,3])
```

Ожидается резульат:

```python
[[2 2 2]
 [2 2 2]
 [2 2 2]]
```

## 1.3 Индексы, маскирование и прихотливое индексирование

[Документация по функциям для работы с индексами](https://pytorch.org/docs/stable/torch.html#indexing-slicing-joining-mutating-ops)

1.3.1 Получить индексы, для которых элементы тензоров `a` и `b` совпадают.

_Пример:_

Для входа:
```python
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
```

Ожидается резульат:

```python
array([1, 3, 5, 7])
```

In [255]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

In [256]:
a = torch.tensor(a)
b = torch.tensor(b)
torch.where(a == b)[0]

tensor([1, 3, 5, 7])

1.3.2 Инвертировать порядок элементов в двумерном тензоре `torch.arange(9).view(3,3)`.

Ожидаемый результат:


```python
array([[8, 7, 6],
       [5, 4, 3],
       [2, 1, 0]])
```

In [15]:
torch.flip(torch.arange(9).view(3,3), [0, 1])

tensor([[8, 7, 6],
        [5, 4, 3],
        [2, 1, 0]])

1.3.3 Из входного тензора a получить только элементы, находящиеся в диапазоне от 5 до 10.

_Пример:_

Для входа:
```python
a = np.array([2, 6, 1, 9, 10, 3, 27])
```

Ожидается резульат:

```python
array([6, 9, 10])
```

In [17]:
a = torch.tensor([2, 6, 1, 9, 10, 3, 27])
a

tensor([ 2,  6,  1,  9, 10,  3, 27])

In [18]:
a[torch.logical_and(10>=a, 5<=a)]

tensor([ 6,  9, 10])

1.3.4 Поменять местами столбец 1 и 2. тензора `np.arange(9).reshape(3,3)`

In [21]:
a = torch.arange(9).reshape(3,3)
print(a)
torch.index_select(a, 1, torch.LongTensor([1,0,2]))

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])


tensor([[1, 0, 2],
        [4, 3, 5],
        [7, 6, 8]])

1.3.5 Создать тензор 8 на 10 из случайных целых чисел из диапазона от 0 до 10 и найти в ней строку (ее индекс и вывести саму строку), в которой сумма значений минимальна.

In [66]:
x = torch.randint(0, 10, (8, 10))
x

tensor([[8, 2, 2, 5, 3, 2, 3, 4, 6, 6],
        [2, 5, 9, 9, 4, 3, 8, 6, 2, 6],
        [6, 9, 3, 5, 4, 8, 2, 9, 7, 6],
        [7, 1, 5, 3, 8, 7, 9, 8, 9, 1],
        [5, 2, 6, 7, 9, 4, 0, 1, 0, 8],
        [2, 8, 8, 2, 1, 6, 4, 7, 3, 8],
        [6, 8, 3, 3, 6, 8, 4, 6, 0, 0],
        [9, 3, 3, 9, 8, 6, 4, 0, 5, 5]])

In [67]:
a = torch.sum(x, 1)
a

tensor([41, 54, 59, 58, 42, 49, 44, 52])

In [68]:
value, ind = torch.min(a, 0)
value, ind

(tensor(41), tensor(0))

In [69]:
ind.item(), x[ind]

(0, tensor([8, 2, 2, 5, 3, 2, 3, 4, 6, 6]))

1.3.6 Cоздать тензор из 20 случайных целых чисел от 0 до 100. Обрезать значения тензора (заменить значения, выходящие за диапазон, на крайние значения) снизу по значению 30, сверху по значению 70.

In [22]:
x = torch.randint(0, 101, (20, ))
x

tensor([33, 17, 65, 14, 77, 40, 64, 91, 19, 84,  4, 42, 51, 85, 21, 11, 84, 15,
        12, 23])

In [23]:
x[x < 30] = 30
x[x > 70] = 70
x

tensor([33, 30, 65, 30, 70, 40, 64, 70, 30, 70, 30, 42, 51, 70, 30, 30, 70, 30,
        30, 30])

In [73]:
a = torch.randint(0, 10, (30, 3))
b = torch.randint(0, 10, (30, 3))
a, b

(tensor([[8, 0, 7],
         [9, 3, 0],
         [2, 1, 4],
         [0, 5, 0],
         [2, 6, 4],
         [3, 4, 8],
         [0, 5, 5],
         [1, 1, 3],
         [6, 5, 5],
         [5, 4, 2],
         [5, 7, 9],
         [5, 4, 4],
         [4, 4, 9],
         [9, 1, 6],
         [6, 1, 6],
         [7, 5, 9],
         [7, 4, 7],
         [0, 6, 2],
         [2, 9, 9],
         [9, 4, 7],
         [7, 3, 6],
         [9, 1, 4],
         [2, 8, 1],
         [3, 0, 2],
         [4, 9, 7],
         [7, 9, 5],
         [2, 4, 2],
         [5, 7, 7],
         [2, 4, 6],
         [5, 9, 2]]),
 tensor([[7, 7, 5],
         [9, 0, 1],
         [1, 3, 2],
         [6, 8, 5],
         [8, 5, 5],
         [2, 7, 9],
         [8, 4, 8],
         [2, 9, 2],
         [1, 8, 6],
         [9, 1, 8],
         [1, 5, 0],
         [9, 0, 9],
         [0, 5, 1],
         [3, 4, 4],
         [5, 5, 9],
         [2, 4, 7],
         [9, 8, 8],
         [8, 3, 3],
         [8, 8, 8],
         [4, 3, 3]

In [77]:
a[a > b]

tensor([8, 7, 3, 2, 4, 6, 3, 5, 3, 6, 4, 5, 7, 9, 4, 4, 9, 9, 6, 6, 7, 5, 9, 6,
        9, 9, 9, 4, 7, 7, 3, 6, 9, 8, 9, 7, 9, 5, 7, 6, 5, 9])

In [76]:
a[a > b].sum()

tensor(265)

1.3.7 Создать два тензора размера 30 на 3 из случайных целых чисел из диапазона от 0 до 10 и найти все значения первого тензора, которые больше соответсвующих (по расположению) значений второго тензора. Подсчитать сумму этих значений.

In [81]:
x = torch.randint(0, 10, (20, 20))
x

tensor([[5, 6, 8, 3, 0, 5, 6, 0, 2, 8, 6, 9, 3, 5, 6, 7, 5, 6, 6, 3],
        [3, 9, 5, 2, 1, 1, 4, 6, 6, 2, 9, 1, 7, 9, 0, 2, 9, 9, 3, 3],
        [8, 1, 6, 3, 7, 2, 4, 0, 4, 1, 4, 2, 0, 1, 4, 8, 4, 6, 3, 6],
        [8, 9, 6, 8, 7, 6, 4, 6, 0, 9, 5, 9, 1, 8, 8, 8, 0, 1, 7, 5],
        [0, 0, 1, 1, 8, 7, 1, 4, 4, 6, 8, 7, 7, 7, 4, 7, 2, 9, 5, 4],
        [7, 1, 0, 8, 0, 0, 0, 0, 1, 8, 2, 9, 0, 1, 5, 0, 3, 4, 8, 7],
        [6, 3, 3, 5, 3, 3, 7, 1, 0, 9, 1, 1, 3, 5, 6, 8, 6, 4, 5, 0],
        [0, 0, 4, 5, 8, 4, 4, 5, 0, 2, 9, 8, 4, 2, 4, 6, 2, 8, 3, 4],
        [5, 1, 4, 7, 8, 8, 9, 6, 2, 0, 4, 5, 5, 8, 5, 3, 6, 9, 4, 8],
        [0, 1, 1, 8, 2, 0, 8, 6, 2, 9, 1, 2, 6, 2, 9, 7, 1, 7, 7, 0],
        [4, 6, 9, 5, 2, 0, 6, 8, 9, 5, 7, 5, 5, 1, 4, 3, 4, 4, 5, 4],
        [8, 0, 4, 0, 4, 6, 8, 4, 8, 2, 6, 2, 0, 6, 1, 5, 7, 4, 7, 4],
        [6, 3, 6, 5, 6, 5, 6, 5, 5, 1, 8, 7, 8, 5, 6, 7, 2, 1, 5, 4],
        [4, 8, 0, 9, 4, 0, 1, 8, 7, 3, 7, 3, 0, 4, 6, 3, 7, 5, 3, 6],
        [6, 0, 2, 3,

In [82]:
torch.diag(x, 1)

tensor([6, 5, 3, 7, 7, 0, 1, 0, 0, 1, 5, 0, 5, 6, 9, 0, 6, 7, 2])

1.3.8 При помощи прихотливого индексирования для двухмерного массива размерности (20, 20), состоящего из случайных целых чисел в пределах от 0 до 10 получить массив элементов находящихся на диагонали, проходящей над основной диагональю.

In [119]:
ar1 = torch.randint(0, 10, (5, 10))
ar2 = torch.randint(0, 10, (5, 10))
ar1, ar2

(tensor([[8, 7, 4, 7, 4, 1, 2, 4, 0, 9],
         [6, 3, 0, 8, 8, 5, 5, 1, 4, 2],
         [8, 9, 2, 4, 0, 7, 0, 7, 9, 2],
         [1, 5, 4, 7, 8, 5, 7, 8, 2, 7],
         [1, 5, 8, 4, 3, 9, 4, 3, 0, 9]]),
 tensor([[9, 2, 5, 8, 6, 7, 1, 7, 4, 8],
         [4, 2, 9, 5, 1, 3, 2, 6, 7, 4],
         [8, 3, 2, 2, 4, 9, 6, 9, 5, 2],
         [2, 8, 8, 6, 0, 7, 7, 6, 5, 5],
         [9, 1, 0, 5, 7, 4, 5, 4, 1, 6]]))

In [121]:
ar1 == ar2

tensor([[False, False, False, False, False, False, False, False, False, False],
        [False, False, False, False, False, False, False, False, False, False],
        [ True, False,  True, False, False, False, False, False, False,  True],
        [False, False, False, False, False, False,  True, False, False, False],
        [False, False, False, False, False, False, False, False, False, False]])

In [122]:
torch.where(ar1==ar2, ar1**2, ar2)

tensor([[ 9,  2,  5,  8,  6,  7,  1,  7,  4,  8],
        [ 4,  2,  9,  5,  1,  3,  2,  6,  7,  4],
        [64,  3,  4,  2,  4,  9,  6,  9,  5,  4],
        [ 2,  8,  8,  6,  0,  7, 49,  6,  5,  5],
        [ 9,  1,  0,  5,  7,  4,  5,  4,  1,  6]])

1.3.9 Задать два двухмерных тензора `ar1` и `ar2` размерности (5, 10), состоящих из случайных целых чисел в пределах от 0 до 10. Удвоить все значения `ar1`, которые совпадают со значениями `ar2`, расположенными на аналогичных позициях.

In [131]:
ar1 = torch.randint(0, 10, (4, 7))
ar2 = torch.randint(0, 10, (4, 7))
ar3 = torch.randint(0, 10, (4, 7))
ar1, ar2, ar3

(tensor([[6, 2, 4, 1, 9, 8, 7],
         [6, 7, 1, 1, 3, 0, 2],
         [0, 8, 9, 2, 1, 3, 3],
         [2, 8, 6, 5, 3, 5, 4]]),
 tensor([[6, 8, 3, 8, 7, 6, 4],
         [3, 2, 5, 3, 1, 3, 8],
         [9, 0, 9, 2, 1, 5, 0],
         [2, 0, 0, 7, 8, 8, 8]]),
 tensor([[7, 1, 7, 5, 7, 2, 1],
         [2, 8, 8, 4, 4, 1, 5],
         [3, 6, 8, 1, 3, 6, 4],
         [6, 9, 0, 1, 7, 2, 5]]))

In [136]:
mask1 = ar1>ar2
mask2 = ar1<ar3

In [138]:
mask1

tensor([[False, False,  True, False,  True,  True,  True],
        [ True,  True, False, False,  True, False, False],
        [False,  True, False, False, False, False,  True],
        [False,  True,  True, False, False, False, False]])

In [139]:
mask2

tensor([[ True, False,  True,  True, False, False, False],
        [False,  True,  True,  True,  True,  True,  True],
        [ True, False, False, False,  True,  True,  True],
        [ True,  True, False, False,  True, False,  True]])

In [149]:
mask = mask1 & mask2
mask

tensor([[False, False,  True, False, False, False, False],
        [False,  True, False, False,  True, False, False],
        [False, False, False, False, False, False,  True],
        [False,  True, False, False, False, False, False]])

In [150]:
ar1[mask] = 0
ar1

tensor([[6, 2, 0, 1, 9, 8, 7],
        [6, 0, 1, 1, 0, 0, 2],
        [0, 8, 9, 2, 1, 3, 0],
        [2, 0, 6, 5, 3, 5, 4]])

1.3.10 Заданы три двухмерных тензора `ar1`, `ar2` и `ar3` размерности (4, 7), состоящие из случайных целых чисел в пределах от 0 до 10. Обнулить все элементы `ar1`, которые больше соответствующих (находящихся в соответствующих позициях) элементов `ar2` и меньше соответствующих элементов `ar3`.

In [151]:
ar1 = torch.randint(0, 20, (20, 5))
ar1

tensor([[19,  2,  4,  3,  6],
        [ 1, 14,  2,  4,  9],
        [12,  3, 18, 13,  2],
        [13,  4, 14, 18,  4],
        [11, 13, 11,  8,  3],
        [13,  6, 18,  5,  7],
        [15,  1,  9,  4,  5],
        [15,  8,  4, 19,  1],
        [10,  6,  4, 14, 14],
        [ 3,  7,  6, 17,  3],
        [ 2,  0,  9,  4, 15],
        [14, 10,  9,  4, 11],
        [ 2, 16,  1,  3, 17],
        [18, 10, 18, 16, 16],
        [16, 14,  4,  8, 17],
        [ 2,  7, 18, 18, 19],
        [ 8,  5, 14,  7,  0],
        [16, 13,  8,  1,  8],
        [ 0,  3, 18,  3,  5],
        [ 8, 10, 13, 10, 12]])

In [153]:
torch.max(ar1, 0)

torch.return_types.max(
values=tensor([19, 16, 18, 19, 19]),
indices=tensor([ 0, 12,  2,  7, 15]))

In [155]:
ar1 == torch.max(ar1, 0).values

tensor([[ True, False, False, False, False],
        [False, False, False, False, False],
        [False, False,  True, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False],
        [False, False,  True, False, False],
        [False, False, False, False, False],
        [False, False, False,  True, False],
        [False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False],
        [False,  True, False, False, False],
        [False, False,  True, False, False],
        [False, False, False, False, False],
        [False, False,  True, False,  True],
        [False, False, False, False, False],
        [False, False, False, False, False],
        [False, False,  True, False, False],
        [False, False, False, False, False]])

In [184]:
torch.sum((ar1 == torch.max(ar1, 0).values), 0)

tensor([1, 1, 5, 1, 1])

In [185]:
more_then_five = torch.sum((ar1 == torch.max(ar1, 0).values), 0) >= 5
more_then_five

tensor([False, False,  True, False, False])

In [188]:
print("Столбец:", torch.where(more_then_five)[0].item() + 1)

Столбец: 3


1.3.12 Задан двумерный тензор `ar1` размерности (4, 7), состоящий из случайных  чисел в пределах от 0 до 1. Обнулить все значения в массиве, расположенные строго правее и ниже максимального элемента массива.

In [200]:
ar1 = torch.rand(4, 7)
ar1

tensor([[0.2559, 0.9207, 0.3171, 0.2286, 0.4639, 0.3292, 0.9362],
        [0.3850, 0.5433, 0.3630, 0.7128, 0.7638, 0.3548, 0.5871],
        [0.6396, 0.5745, 0.1387, 0.2900, 0.9930, 0.6333, 0.4608],
        [0.8247, 0.5364, 0.0889, 0.8417, 0.4360, 0.8216, 0.2623]])

In [201]:
ar1.max()

tensor(0.9930)

In [206]:
ar1 == ar1.max()

tensor([[False, False, False, False, False, False, False],
        [False, False, False, False, False, False, False],
        [False, False, False, False,  True, False, False],
        [False, False, False, False, False, False, False]])

In [202]:
x, y = torch.where(ar1 == ar1.max())
x, y

(tensor([2]), tensor([4]))

In [205]:
ar1[:x+1, :y+1]

tensor([[0.2559, 0.9207, 0.3171, 0.2286, 0.4639],
        [0.3850, 0.5433, 0.3630, 0.7128, 0.7638],
        [0.6396, 0.5745, 0.1387, 0.2900, 0.9930]])

1.3.12 Задан двумерный тензор `ar1` размерности (4, 7), состоящий из случайных  чисел в пределах от 0 до 1. Обнулить все значения в массиве, расположенные строго правее и ниже максимального элемента массива. 

In [321]:
x = torch.tensor([2, 3, 2, 2, 2, 1])
x

tensor([2, 3, 2, 2, 2, 1])

In [344]:
torch.nn.functional.one_hot(x)[:, 1:]

tensor([[0, 1, 0],
        [0, 0, 1],
        [0, 1, 0],
        [0, 1, 0],
        [0, 1, 0],
        [1, 0, 0]])

1.3.14 Создать тензор `arr` из 20 случайных целых чисел от 0 до 100. Найти самое частое значение в тензоре. 
Найти индексы в тензоре, соответствующие самому частому значению. Проверить, как работет алгоритм при двух значениях, имеющих наибольшую встречаемость, предложить приемлемое поведение алгоритма для этого случая.

In [345]:
arr = torch.randint(0, 100, (20, ))
arr

tensor([63, 14,  0, 23, 27, 21, 44, 99, 57, 79, 69, 67, 62, 91,  6, 69, 78, 22,
        68, 27])

In [346]:
bc = torch.bincount(arr)
bc

tensor([1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1,
        0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 2, 0, 0,
        0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
        0, 0, 0, 1])

In [348]:
ind = torch.where(bc == bc.max(0)[0])[0]
ind

tensor([27, 69])

In [353]:
torch.isin(arr, ind)

tensor([False, False, False, False,  True, False, False, False, False, False,
         True, False, False, False, False,  True, False, False, False,  True])

In [358]:
print("Индексы: ", torch.where(torch.isin(arr, ind))[0].tolist())

Индексы:  [4, 10, 15, 19]


1.3.14 Создать тензор `arr` из 20 случайных целых чисел от 0 до 100. Найти самое частое значение в тензоре. 
Найти индексы в тензоре, соответствующие самому частому значению. Проверить, как работет алгоритм при двух значениях, имеющих наибольшую встречаемость, предложить приемлемое поведение алгоритма для этого случая. 

## 1.4 Математические задачи

In [315]:
x = torch.arange(11)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [316]:
x = x*torch.sin(x)
x

tensor([ 0.0000,  0.8415,  1.8186,  0.4234, -3.0272, -4.7946, -1.6765,  4.5989,
         7.9149,  3.7091, -5.4402])

1.4.1 Приблизительно (с погрешностью порядка 1%) рассчитать на какой части интервала от 0 до 10 значение функции x * sin(x) больше 0.5.

In [320]:
numbers = torch.arange(2, 101)
numbers

tensor([  2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,  14,  15,
         16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,  28,  29,
         30,  31,  32,  33,  34,  35,  36,  37,  38,  39,  40,  41,  42,  43,
         44,  45,  46,  47,  48,  49,  50,  51,  52,  53,  54,  55,  56,  57,
         58,  59,  60,  61,  62,  63,  64,  65,  66,  67,  68,  69,  70,  71,
         72,  73,  74,  75,  76,  77,  78,  79,  80,  81,  82,  83,  84,  85,
         86,  87,  88,  89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99,
        100])

1.4.2 Найти все простые числа в пределах ста. (Для решения предлагается использовать Решето Эратосфена) Использовать не более 1 цикла (желательно).

1.4.3 Найти евклидово расстояние между двумя одномерными тензорами одинаковой размерности, не используя готовые решения из библиотек.

In [362]:
x = torch.randint(0, 101, (20, 3), dtype=float)
x

tensor([[ 29.,  50.,  27.],
        [  6.,  86.,   0.],
        [ 27.,  33.,  86.],
        [  2.,   7.,  49.],
        [ 34.,  82.,   8.],
        [ 14.,  34.,   3.],
        [ 25.,  16.,  73.],
        [100.,  51.,  10.],
        [ 44.,  44.,  96.],
        [ 92.,  13.,  72.],
        [ 40.,  67.,  42.],
        [ 53.,  66.,  26.],
        [ 99.,   1.,   3.],
        [ 54.,  52.,  26.],
        [ 87.,  47.,  40.],
        [ 76.,  94.,  57.],
        [100.,   9.,  93.],
        [ 43.,  23.,  18.],
        [ 68.,   2.,  11.],
        [ 83.,  37.,  21.]], dtype=torch.float64)

In [370]:
x.norm(dim=1, p=2).squeeze(-1)

tensor([ 63.7966,  86.2090,  95.9896,  49.5379,  89.1291,  36.8917,  78.8036,
        112.6987, 114.4028, 117.5457,  88.6172,  88.5494,  99.0505,  79.3473,
        106.6677, 133.6451, 136.8576,  51.9808,  68.9130,  93.2684],
       dtype=torch.float64)

In [367]:
torch.argsort(x, dim=1)

tensor([[2, 0, 1],
        [2, 0, 1],
        [0, 1, 2],
        [0, 1, 2],
        [2, 0, 1],
        [2, 0, 1],
        [1, 0, 2],
        [2, 1, 0],
        [0, 1, 2],
        [1, 2, 0],
        [0, 2, 1],
        [2, 0, 1],
        [1, 2, 0],
        [2, 1, 0],
        [2, 1, 0],
        [2, 0, 1],
        [1, 2, 0],
        [2, 1, 0],
        [1, 2, 0],
        [2, 1, 0]])

1.4.4 Создать двумерный тензор 20 на 3, содержащий случайные целые числа от 0 до 100. 
Интерпретируя тензор как 20 векторов из 3х компонент, отсортировать его по длине векторов.

1.4.5 Найти "локальные максимумы" в одномерном тензоре (т.е. значения, большие предыдущего и последующего) `torch.tensor([1, 3, 7, 1, 2, 6, 0, 1])` и вывести их индексы.

1.4.6 Задан произвольный массив numpy (например массив из 100 случайных числе от 0 до 1). Необходимо найти в нем число наиболее близкое к заданному.

1.4.7 Решить матричное уравнение `A*X*B=-C` - найти матрицу X. Где `A = [[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]]`, `B=[[3, -1], [2, 1]]`, `C=[[7, 21], [11, 8], [8, 4]]`.

1.4.8 Проверить, является ли система векторов a1 = (3; −3; 0; 7),
a2 = (2; 2; 4; 7), a3 = (1; 2; 3; 4), a4 = (5; −4; 1; 3) линейно зависимой?

1.4.9 Сгенирировать тензор из 200 случайных целых чисел, нормально распрделенных cо стандартным отклонением $\sigma = 10$ и матожиданием $\mu = 0$. Построить тензор гистограммы с 20 бинами. 